name: Deploy

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "morning-beyond-server"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: "web: npm run jsonserver"
